"""empty message

Revision ID: 327e5b447713
Revises: 740c9ae30a03
Create Date: 2020-03-21 22:24:23.202301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327e5b447713'
down_revision = '740c9ae30a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ingredient_stock_ingredient_id_fkey', 'ingredient_stock', type_='foreignkey')
    op.drop_constraint('ingredient_stock_user_id_fkey', 'ingredient_stock', type_='foreignkey')
    op.create_foreign_key(None, 'ingredient_stock', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ingredient_stock', 'ingredient', ['ingredient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('recipe_ingredient_ingredient_id_fkey', 'recipe_ingredient', type_='foreignkey')
    op.drop_constraint('recipe_ingredient_recipe_id_fkey', 'recipe_ingredient', type_='foreignkey')
    op.create_foreign_key(None, 'recipe_ingredient', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recipe_ingredient', 'ingredient', ['ingredient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_ingredient', type_='foreignkey')
    op.drop_constraint(None, 'recipe_ingredient', type_='foreignkey')
    op.create_foreign_key('recipe_ingredient_recipe_id_fkey', 'recipe_ingredient', 'recipe', ['recipe_id'], ['id'])
    op.create_foreign_key('recipe_ingredient_ingredient_id_fkey', 'recipe_ingredient', 'ingredient', ['ingredient_id'], ['id'])
    op.drop_constraint(None, 'ingredient_stock', type_='foreignkey')
    op.drop_constraint(None, 'ingredient_stock', type_='foreignkey')
    op.create_foreign_key('ingredient_stock_user_id_fkey', 'ingredient_stock', 'user', ['user_id'], ['id'])
    op.create_foreign_key('ingredient_stock_ingredient_id_fkey', 'ingredient_stock', 'ingredient', ['ingredient_id'], ['id'])
    # ### end Alembic commands ###
